STATUS_OK = 0
STATUS_UNKNOWN = 1
STATUS_INFO = 2
STATUS_WARNING = 3
STATUS_ERROR = 4
STATUS_CHOICES = (
    (STATUS_OK, 'success'),
    (STATUS_UNKNOWN, ''),
    (STATUS_INFO, 'info'),
    (STATUS_WARNING, 'warning'),
    (STATUS_ERROR, 'danger'),
)

ALERT_INFO_LOAD = 5
ALERT_INFO_SEEN = 4
ALERT_WARNING_LOAD = 7
ALERT_WARNING_SEEN = 6
ALERT_DANGER_LOAD = 10
ALERT_DANGER_SEEN = 10
